<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Region;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regions = [
            'Karakalpakstan Republic' => [
                'Amudaryo',
                'Beruniy',
                'Chimboy',
                'Ellikqala',
                'Kegeyli',
                'Moʻynoq',
                'Nukus',
                'Qanlikoʻl',
                'Qoʻngʻirot',
                'Qoraoʻzak',
                'Shumanay',
                'Taxtakoʻpir',
                'Toʻrtkoʻl',
                'Xoʻjayli',
                'Taxiatosh',
                'Boʻzatov',
            ],
            'Tashkent' => [
                'Bektemir',
                'Chilonzor',
                'Hamza (Yashnobod)',
                'Mirobod',
                'Mirzo Ulugbek',
                'Sergeli',
                'Shaykhantohur',
                'Olmazor',
                'Uchtepa',
                'Yakkasaray',
                'Yunusabad',
                'Yashnobod',
            ],
            'Tashkent region' => [
                'Bekabad',
                'Boʻstonliq',
                'Boʻka',
                'Chinoz',
                'Qibray',
                'Ohangaron',
                'Oqqoʻrgʻon',
                'Parkent',
                'Piskent',
                'Quyichirchiq',
                'Zangiota',
                'Oʻrtachirchiq',
                'Yangiyoʻl',
                'Yuqorichirchiq',
                'Tashkent',
            ],
            'Andijan' => [
                'Andijan',
                'Asaka',
                'Baliqchi',
                'Boʻston',
                'Buloqboshi',
                'Izboskan',
                'Jalaquduq',
                'Xoʻjaobod',
                'Qoʻrgʻontepa',
                'Marhamat',
                'Oltinkoʻl',
                'Paxtaobod',
                'Shahrixon',
                'Ulugʻnor',
            ],
            'Bukhara' => [
                'Olot',
                'Bukhara',
                'Gʻijduvon',
                'Jondor',
                'Kogon',
                'Qorakoʻl',
                'Qorovulbozor',
                'Peshku',
                'Romitan',
                'Shofirkon',
                'Vobkent',
            ],
            'Fergana' => [
                'Oltiariq',
                'Bagʻdod',
                'Beshariq',
                'Buvayda',
                'Dangʻara',
                'Fergana',
                'Furqat',
                'Qoʻshtepa',
                'Quva',
                'Rishton',
                'Soʻx',
                'Toshloq',
                'Uchkoʻprik',
                'Uzbekistan',
                'Yozyovon',
            ],
            'Jizzakh' => [
                'Arnasay',
                'Bakhmal',
                'Dustlik',
                'Forish',
                'Gallaorol',
                'Jizzakh',
                'Mirzachul',
                'Pakhtakor',
                'Yangiobod',
                'Zafarobod',
                'Zarbdor',
                'Zomin',
            ],
            'Namangan' => [
                'Chortoq',
                'Chust',
                'Kosonsoy',
                'Mingbuloq',
                'Namangan',
                'Norin',
                'Pop',
                'Toʻraqoʻrgʻon',
                'Uchqoʻrgʻon',
                'Uychi',
                'Yangiqoʻrgʻon',
                'Yangi Namangan',
            ],
            'Navoiy' => [
                'Karmana',
                'Konimex',
                'Khatirchi',
                'Navbahor',
                'Nurota',
                'Qiziltepa',
                'Tomdi',
                'Uchquduq',
            ],
            'Kashkadarya' => [
                'Chiroqchi',
                'Dehqonobod',
                'Gʻuzor',
                'Kasbi',
                'Kitob',
                'Koson',
                'Mirishkor',
                'Muborak',
                'Nishon',
                'Qamashi',
                'Qarshi',
                'Shahrisabz',
                'Yakkabogʻ',
            ],
            'Samarkand' => [
                'Bulungʻur',
                'Ishtixon',
                'Jomboy',
                'Kattakurgan',
                'Qoʻshrabot',
                'Narpay',
                'Nurobod',
                'Oqdaryo',
                'Paxtachi',
                'Payariq',
                'Pastdargʻom',
                'Samarkand',
                'Toyloq',
                'Urgut',
            ],
            'Surkhandarya' => [
                'Angor',
                'Bandixon',
                'Boysun',
                'Denov',
                'Jarqoʻrgʻon',
                'Muzrabot',
                'Oltinsoy',
                'Qiziriq',
                'Qumqoʻrgʻon',
                'Sherobod',
                'Shorchi',
                'Termiz',
                'Uzun',
            ],
            'Sirdarya' => [
                'Akaltyn',
                'Boyovut',
                'Guliston',
                'Khavast',
                'Mirzaobod',
                'Sardoba',
                'Saykhunobod',
                'Sirdaryo',
                'Yangiyer',
            ],
            'Khorezm' => [
                'Bogʻot',
                'Gurlan',
                'Khiva',
                'Khazarasp',
                'Khonqa',
                'Qoʻshkoʻpir',
                'Shovot',
                'Urganch',
                'Yangiariq',
                'Yangibozor',
            ],
        ];


        foreach ($regions as $regionName => $districts) {
            $region = Region::where('title', $regionName)->first();

            foreach ($districts as $district) {
                District::create([
                    'region_id' => $region->id,
                    'title' => $district,
                ]);
            }
        }
    }
}